/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class bookingroom extends javax.swing.JFrame {

    /**
     * Creates new form bookingroom
     */
    public bookingroom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    int numberofday;
    int totalcost;
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AC = new javax.swing.JCheckBox();
        NONAC = new javax.swing.JCheckBox();
        Days = new javax.swing.JComboBox<>();
        day = new javax.swing.JLabel();
        cost = new javax.swing.JTextField();
        TCost = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        AC.setText("AC");
        AC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACActionPerformed(evt);
            }
        });
        jPanel1.add(AC);
        AC.setBounds(21, 64, 91, 23);

        NONAC.setText("Non AC");
        jPanel1.add(NONAC);
        NONAC.setBounds(21, 106, 61, 23);

        Days.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 ", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(Days);
        Days.setBounds(91, 0, 91, 20);

        day.setText("Days Of Stay");
        jPanel1.add(day);
        day.setBounds(21, 0, 91, 20);

        cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costActionPerformed(evt);
            }
        });
        jPanel1.add(cost);
        cost.setBounds(247, 142, 119, 31);
        jPanel1.add(TCost);
        TCost.setBounds(91, 251, 149, 36);

        jLabel2.setText("Cost");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(275, 102, 36, 30);

        jLabel3.setText("Total Cost");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(91, 216, 65, 29);

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(91, 150, 77, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\dining.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 410, 330);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costActionPerformed

    private void ACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ACActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //String temp=Days.getItemAt((int) Days.getSelectedItem());
        //numberofday=Integer.parseInt(temp);
        int temp2=0;
        numberofday=Days.getSelectedIndex();
        boolean isSelected= AC.isSelected();
        boolean isSelected1= NONAC.isSelected();
        if(isSelected && !isSelected1)
        {
             
             temp2=1500*(numberofday+1);
            cost.setText(Integer.toString(1500));
        }
        if(isSelected1 &&!isSelected)
        {
             temp2=1000*(numberofday+1);
            
            cost.setText(Integer.toString(1000));
        }
       
        TCost.setText(Integer.toString(temp2));
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookingroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookingroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookingroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookingroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookingroom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AC;
    private javax.swing.JComboBox<String> Days;
    private javax.swing.JCheckBox NONAC;
    private javax.swing.JTextField TCost;
    private javax.swing.JTextField cost;
    private javax.swing.JLabel day;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
